# Generated by Django 5.2.6 on 2025-10-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_base',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_cliente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_distribuidor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
