# Generated by Django 5.2.6 on 2025-10-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio_final',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_vendido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('cliente', 'Cliente Final'), ('distribuidor', 'Distribuidor')], default='cliente', max_length=20),
        ),
    ]
